### ISSUE TITLE
When i use in angular following the instructions weavy throws this...

### ISSUE THREAD

**Issue by nesgarbo** [weavy/weavy-uikit-web#2]
Application bundle generation failed. [5.356 seconds]
[ng] X [ERROR] TS2307: Cannot find module '../../@microsoft/signalr/dist/browser/signalr.min.js' or its corresponding type declarations. [plugin angular-compiler]
[ng]
[ng]     node_modules/@weavy/uikit-web/dist/types/client/connection.d.ts:3:30:
[ng]       3 │ ...tion } from '../../@microsoft/signalr/dist/browser/signalr.min.js';
[ng]         ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]
[ng] X [ERROR] TS2307: Cannot find module '../../@microsoft/signalr/dist/browser/signalr.min.js' or its corresponding type declarations. [plugin angular-compiler]
[ng]
[ng]     node_modules/@weavy/uikit-web/dist/types/client/weavy.d.ts:104:29:
[ng]       104 │ ...?: import('../../@microsoft/signalr/dist/browser/signalr.min.j...
[ng]           ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]
[ng] X [ERROR] TS2307: Cannot find module '../../@microsoft/signalr/dist/browser/signalr.min.js' or its corresponding type declarations. [plugin angular-compiler]
[ng]
[ng]     node_modules/@weavy/uikit-web/dist/types/client/weavy.d.ts:113:39:
[ng]       113 │ ...n: import('../../@microsoft/signalr/dist/browser/signalr.min.j...
[ng]           ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]
[ng] X [ERROR] TS2339: Property 'getChatToken' does not exist on type 'WeavyService'. [plugin angular-compiler]
[ng]
[ng]     src/app/chat/chat.component.ts:18:42:
[ng]       18 │     const token = await this.weavyService.getChatToken(userId);
[ng]          ╵                                           ~~~~~~~~~~~~
[ng]
[ng]
[ng] X [ERROR] TS2339: Property 'initializeWeavy' does not exist on type 'WeavyService'. [plugin angular-compiler]
[ng]
[ng]     src/app/chat/chat.component.ts:21:30:
[ng]       21 │ ...await this.weavyService.initializeWeavy(token, { key: 'chat-spa...
[ng]          ╵                            ~~~~~~~~~~~~~~~
[ng]
[ng]
[ng] X [ERROR] TS2339: Property 'loadChatComponent' does not exist on type 'WeavyService'. [plugin angular-compiler]
[ng]
[ng]     src/app/chat/chat.component.ts:22:24:
[ng]       22 │       this.weavyService.loadChatComponent(this.chatContainer()!);
[ng]          ╵                         ~~~~~~~~~~~~~~~~~
[ng]
[ng]
[ng] - Changes detected. Rebuilding...
[ng] Application bundle generation failed. [0.233 seconds]
[ng] X [ERROR] TS2307: Cannot find module '../../@microsoft/signalr/dist/browser/signalr.min.js' or its corresponding type declarations. [plugin angular-compiler]
[ng]
[ng]     node_modules/@weavy/uikit-web/dist/types/client/connection.d.ts:3:30:
[ng]       3 │ ...tion } from '../../@microsoft/signalr/dist/browser/signalr.min.js';
[ng]         ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]
[ng] X [ERROR] TS2307: Cannot find module '../../@microsoft/signalr/dist/browser/signalr.min.js' or its corresponding type declarations. [plugin angular-compiler]
[ng]
[ng]     node_modules/@weavy/uikit-web/dist/types/client/weavy.d.ts:104:29:
[ng]       104 │ ...?: import('../../@microsoft/signalr/dist/browser/signalr.min.j...
[ng]           ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]
[ng] X [ERROR] TS2307: Cannot find module '../../@microsoft/signalr/dist/browser/signalr.min.js' or its corresponding type declarations. [plugin angular-compiler]
[ng]
[ng]     node_modules/@weavy/uikit-web/dist/types/client/weavy.d.ts:113:39:
[ng]       113 │ ...n: import('../../@microsoft/signalr/dist/browser/signalr.min.j...
[ng]           ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]
[ng] X [ERROR] TS-992008: Could not find stylesheet file './chat.component.css'. [plugin angular-compiler]
[ng]
[ng]     src/app/chat/chat.component.ts:9:12:
[ng]       9 │   styleUrl: "./chat.component.css",
[ng]         ╵             ~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]
[ng] - Changes detected. Rebuilding...
[ng] Application bundle generation failed. [0.212 seconds]
[ng] X [ERROR] TS2307: Cannot find module '../../@microsoft/signalr/dist/browser/signalr.min.js' or its corresponding type declarations. [plugin angular-compiler]
[ng]
[ng]     node_modules/@weavy/uikit-web/dist/types/client/connection.d.ts:3:30:
[ng]       3 │ ...tion } from '../../@microsoft/signalr/dist/browser/signalr.min.js';
[ng]         ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]
[ng] X [ERROR] TS2307: Cannot find module '../../@microsoft/signalr/dist/browser/signalr.min.js' or its corresponding type declarations. [plugin angular-compiler]
[ng]
[ng]     node_modules/@weavy/uikit-web/dist/types/client/weavy.d.ts:104:29:
[ng]       104 │ ...?: import('../../@microsoft/signalr/dist/browser/signalr.min.j...
[ng]           ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]
[ng]
[ng] X [ERROR] TS2307: Cannot find module '../../@microsoft/signalr/dist/browser/signalr.min.js' or its corresponding type declarations. [plugin angular-compiler]
[ng]
[ng]     node_modules/@weavy/uikit-web/dist/types/client/weavy.d.ts:113:39:
[ng]       113 │ ...n: import('../../@microsoft/signalr/dist/browser/signalr.min.j...

**Comment by klasjersevi** [comment]
We just released Weavy v24.0.0 which has some fixes for the build. Could you try and see if it resolves your issue?

**Comment by nesgarbo** [comment]
I'll try, thx

**Comment by nesgarbo** [comment]
> We just released Weavy v24.0.0 which has some fixes for the build. Could you try and see if it resolves your issue?

I have done everything but everywhere says it is still the other version (23)

![image](https://github.com/weavy/weavy-uikit-web/assets/60317435/8e763992-f67c-4e57-84e5-a06e0cc47c32)

**Comment by klasjersevi** [comment]
You need to upgrade both the @weavy/uikit-web npm package and your environment to v24.0.0 in your account at https://weavy.com as well. 

Please share the package.json file for your project if you still experience build problems after upgrading to v24.0.0.

**Comment by nesgarbo** [comment]
Ok, mb. I realized that I hadn't recompiled the core.

Now it is already 24.0.0, and weavy-uikit-web is showing the same error. I'm using Angular 18 and esbuild.

Any recommendations?

**Comment by klasjersevi** [comment]
Ok, I think I need more info here. Did you install the npm package or are you using the GitHub repo? If you could share your package.json, that would help.

**Comment by nesgarbo** [comment]
I have installed the npm package and it works fine in an angular 18 project, but not in an ionic one.
In this one i have just created for example throws same error:
The package.json:
"@angular/animations": "^18.0.0",
    "@angular/common": "^18.0.0",
    "@angular/compiler": "^18.0.0",
    "@angular/core": "^18.0.0",
    "@angular/forms": "^18.0.0",
    "@angular/platform-browser": "^18.0.0",
    "@angular/platform-browser-dynamic": "^18.0.0",
    "@angular/router": "^18.0.0",
    "@capacitor/app": "6.0.0",
    "@capacitor/core": "6.1.0",
    "@capacitor/haptics": "6.0.0",
    "@capacitor/keyboard": "6.0.1",
    "@capacitor/status-bar": "6.0.0",
    "@ionic/angular": "^8.0.0",
    "@weavy/uikit-web": "^24.0.1",
    "ionicons": "^7.2.1",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"

![CleanShot 2024-07-15 at 12 38 47@2x](https://github.com/user-attachments/assets/c9eef415-2636-4aea-af20-e15127c3a7a0)
![CleanShot 2024-07-15 at 12 39 27@2x](https://github.com/user-attachments/assets/a7d88fe0-9c2c-45b9-97e4-b6138e100ade)

**Comment by klasjersevi** [comment]
Thank you for the info. You can try installing the `@microsoft/signalr` package as a workaround. I'll take a deeper look at this when I'm back from vacation.

**Comment by klasjersevi** [comment]
@nesgarbo We've made some build adjustments in the last releases. Are you still experiencing this issue?

**Comment by goranvujanovicvelora** [comment]
I am using Angular 20 and I have this error:
[ERROR] TS2307: Cannot find module 'node:stream/web' or its corresponding type declarations. [plugin angular-compiler] [ng] node_modules/@napi-rs/canvas/index.

**Comment by klasjersevi** [comment]
@goranvujanovicvelora 

> I am using Angular 20 and I have this error: [ERROR] TS2307: Cannot find module 'node:stream/web' or its corresponding type declarations. [plugin angular-compiler] [ng] node_modules/@napi-rs/canvas/index.

I just tried creating an Angular 20 app and added Weavy v29.2.0 to it without any problems.

I used the following guides:
* [Angular Installation](https://angular.dev/installation)
* [Add Weavy to your app built with Angular](https://www.weavy.com/technologies/angular/get-started) (with some minor adjustments of file names according to Angular 20).

The issue may be related to your code or another package as suggested in https://github.com/angular/angular-cli/issues/30657
